const f = (id, subtopic, prompt, answer, distractors, explanation, details, difficulty, source, aliases = []) => ({ id, subtopics: [subtopic], prompt, answer, aliases, distractors, explanation, details, difficulty, source });
const pack = {
  packSlug: "american-story", topicSlug: "history",
  sources: {
    indigenous: { label: "National Museum of the American Indian", url: "https://americanindian.si.edu/nk360" },
    colonial: { label: "OpenStax U.S. History", url: "https://openstax.org/books/us-history/pages/3-introduction" },
    revolution: { label: "OpenStax U.S. History", url: "https://openstax.org/books/us-history/pages/6-introduction" },
    constitution: { label: "U.S. National Archives", url: "https://www.archives.gov/founding-docs/constitution" },
    civilwar: { label: "OpenStax U.S. History", url: "https://openstax.org/books/us-history/pages/15-introduction" },
    industry: { label: "OpenStax U.S. History", url: "https://openstax.org/books/us-history/pages/18-introduction" },
    immigration: { label: "OpenStax U.S. History", url: "https://openstax.org/books/us-history/pages/19-introduction" },
    rights: { label: "National Park Service Civil Rights", url: "https://www.nps.gov/subjects/civilrights/index.htm" },
    foreign: { label: "Office of the Historian, U.S. Department of State", url: "https://history.state.gov/milestones" },
    culture: { label: "Smithsonian Institution", url: "https://www.si.edu/spotlight/american-history" },
  },
  facts: [
    f("indigenous-three-sisters", "Indigenous History", "Corn, beans, and squash are traditionally grown together under what collective name?", "Three Sisters", ["Four Directions", "Sacred Hoop", "Green Corn Road"], "The Three Sisters planting system combines crops that support one another.", "Corn provides a climbing stalk, beans add nitrogen to soil, and broad squash leaves help suppress weeds and retain moisture.", 1, "indigenous", ["The Three Sisters"]),
    f("indigenous-cahokia", "Indigenous History", "Which large Mississippian city flourished near present-day St. Louis?", "Cahokia", ["Mesa Verde", "Chaco Canyon", "Poverty Point"], "Cahokia was the largest known urban center north of Mexico in pre-Columbian America.", "Its plazas and earthen mounds, including Monks Mound, reflect a populous and politically organized regional society.", 2, "indigenous"),
    f("indigenous-haudenosaunee", "Indigenous History", "What confederacy united the Mohawk, Oneida, Onondaga, Cayuga, and Seneca nations?", "Haudenosaunee Confederacy", ["Powhatan Confederacy", "Wabanaki Confederacy", "Blackfoot Confederacy"], "The Haudenosaunee Confederacy is also called the Iroquois Confederacy.", "Its Great Law of Peace established a council system; the Tuscarora later joined as a sixth nation.", 3, "indigenous", ["Iroquois Confederacy", "Five Nations", "Six Nations"]),
    f("indigenous-pueblo", "Indigenous History", "Which peoples of the Southwest are known for multistory settlements built from stone and adobe?", "Pueblo peoples", ["Inuit peoples", "Seminole peoples", "Tlingit peoples"], "Pueblo communities developed durable apartment-like settlements adapted to arid environments.", "Their diverse nations include Hopi, Zuni, Acoma, Taos, and others with distinct languages and traditions.", 3, "indigenous", ["Puebloans", "Pueblo"]),
    f("indigenous-potlach", "Indigenous History", "What ceremonial feast of Pacific Northwest peoples centers on gift giving and redistribution?", "Potlatch", ["Powwow", "Kiva", "Sun Dance"], "A potlatch affirms status, kinship, history, and responsibility through feasting and gifts.", "Colonial governments once prohibited the practice, but communities preserved and revitalized it.", 4, "indigenous"),

    f("colonial-thirteen", "Colonial America", "How many British colonies declared independence in 1776?", "13", ["10", "12", "15"], "Thirteen British colonies formed the original United States.", "Their borders, economies, religions, and political institutions varied substantially despite their joint break with Britain.", 1, "colonial", ["Thirteen"]),
    f("colonial-mayflower", "Colonial America", "Which 1620 agreement created a framework for self-government among Plymouth settlers?", "Mayflower Compact", ["Fundamental Orders", "Albany Plan", "Virginia Resolves"], "The Mayflower Compact pledged signers to form a civil political body and obey agreed laws.", "It was not a constitution for democracy, but it became a prominent symbol of government by covenant and consent.", 2, "colonial", ["The Mayflower Compact"]),
    f("colonial-burgesses", "Colonial America", "What was the elected representative assembly founded in Virginia in 1619 called?", "House of Burgesses", ["General Court", "Continental Congress", "Privy Council"], "The House of Burgesses was the first representative legislative assembly in English North America.", "Its authority remained limited by the governor, company, crown, and a political system that excluded most residents.", 3, "colonial", ["Virginia House of Burgesses"]),
    f("colonial-awakening", "Colonial America", "What name is given to the religious revival that swept British North America in the 1730s and 1740s?", "First Great Awakening", ["Second Great Awakening", "Social Gospel", "Restoration Movement"], "The First Great Awakening emphasized personal conversion and emotionally powerful preaching.", "It challenged established churches, encouraged new denominations, and created shared experiences across colonial boundaries.", 3, "colonial", ["Great Awakening"]),
    f("colonial-salutary", "Colonial America", "What term describes Britain's long period of loosely enforcing many colonial trade rules?", "Salutary neglect", ["Home rule", "Mercantilist repeal", "Virtual representation"], "Salutary neglect allowed colonial merchants and assemblies considerable practical autonomy.", "Britain's tighter postwar enforcement after 1763 contributed to conflict over taxation, trade, and political authority.", 4, "colonial"),

    f("revolution-declaration", "American Revolution", "Which document announced that the thirteen colonies considered themselves independent states?", "Declaration of Independence", ["Constitution", "Bill of Rights", "Articles of Confederation"], "The Declaration of Independence announced separation from Britain in 1776.", "Its argument combined specific grievances with claims about equality, natural rights, consent, and the right to alter government.", 1, "revolution", ["The Declaration of Independence"]),
    f("revolution-lexington", "American Revolution", "At which two Massachusetts towns did fighting open the American Revolutionary War?", "Lexington and Concord", ["Yorktown and Jamestown", "Trenton and Princeton", "Saratoga and Albany"], "British regulars and colonial militia fought at Lexington and Concord in April 1775.", "The expedition sought military supplies at Concord, while riders spread warnings that mobilized militia along the return route.", 2, "revolution"),
    f("revolution-valley-forge", "American Revolution", "Where did Washington's Continental Army endure the difficult winter of 1777–1778?", "Valley Forge", ["Fort Ticonderoga", "Bunker Hill", "Morristown Harbor"], "Valley Forge became a symbol of hardship and army reform.", "Supply failures caused severe suffering, while training associated with Friedrich von Steuben improved discipline and standardized drills.", 3, "revolution"),
    f("revolution-saratoga", "American Revolution", "Which American victory helped persuade France to enter the Revolutionary War openly?", "Saratoga", ["Camden", "Long Island", "Charleston"], "The British surrender at Saratoga helped secure a formal French alliance.", "French money, weapons, troops, naval power, and global pressure substantially changed the strategic balance against Britain.", 3, "revolution", ["Battle of Saratoga", "Battles of Saratoga"]),
    f("revolution-federalist", "American Revolution", "Which three authors wrote the Federalist Papers under the name Publius?", "Hamilton, Madison, and Jay", ["Adams, Franklin, and Paine", "Jefferson, Monroe, and Henry", "Washington, Knox, and Morris"], "Alexander Hamilton, James Madison, and John Jay wrote the Federalist essays.", "The essays defended the proposed Constitution and remain influential explanations of federalism, institutional design, and republican government.", 4, "revolution", ["Alexander Hamilton James Madison and John Jay", "Hamilton Madison Jay"]),

    f("constitution-branches", "Constitutional History", "How many branches of the federal government are established by the Constitution?", "3", ["2", "4", "5"], "The Constitution establishes legislative, executive, and judicial branches.", "Separated powers and overlapping checks are intended to prevent authority from concentrating in one institution.", 1, "constitution", ["Three"]),
    f("constitution-bill-rights", "Constitutional History", "What collective name is given to the first ten amendments?", "Bill of Rights", ["Federalist Papers", "Reconstruction Acts", "Articles of Union"], "The Bill of Rights protects specified liberties and limits federal power.", "Ratified in 1791, the amendments address expression, religion, criminal procedure, arms, federalism, and other rights.", 2, "constitution", ["The Bill of Rights"]),
    f("constitution-great-compromise", "Constitutional History", "Which convention agreement created a House based on population and a Senate with equal state representation?", "Great Compromise", ["Missouri Compromise", "Compromise of 1850", "Three-Fifths Compromise"], "The Great Compromise created the basic structure of Congress.", "It reconciled competing large-state and small-state plans through a bicameral legislature with different bases of representation.", 3, "constitution", ["Connecticut Compromise"]),
    f("constitution-marbury", "Constitutional History", "Which Supreme Court case firmly established judicial review of federal laws?", "Marbury v. Madison", ["McCulloch v. Maryland", "Gibbons v. Ogden", "Dred Scott v. Sandford"], "Marbury v. Madison asserted the Supreme Court's authority to invalidate unconstitutional federal legislation.", "Chief Justice John Marshall reasoned that courts must apply the Constitution when an ordinary law conflicts with it.", 3, "constitution", ["Marbury versus Madison", "Marbury"]),
    f("constitution-electoral-college", "Constitutional History", "What constitutional body formally chooses the president and vice president?", "Electoral College", ["Cabinet", "Supreme Court", "Senate alone"], "Presidential electors cast the formal votes counted to determine the election winner.", "Each state's allocation equals its total representation in Congress, while the District of Columbia receives electors under the Twenty-Third Amendment.", 4, "constitution", ["The Electoral College"]),

    f("expansion-louisiana", "Expansion & Civil War", "Which 1803 acquisition roughly doubled the territory claimed by the United States?", "Louisiana Purchase", ["Alaska Purchase", "Gadsden Purchase", "Mexican Cession"], "The Louisiana Purchase transferred France's North American claim to the United States.", "The acquisition secured New Orleans and the Mississippi outlet while raising lasting questions about Indigenous sovereignty and slavery's expansion.", 1, "civilwar", ["The Louisiana Purchase"]),
    f("expansion-underground", "Expansion & Civil War", "What was the secret network that helped freedom seekers escape slavery called?", "Underground Railroad", ["National Road", "Freedom Trail", "Oregon Trail"], "The Underground Railroad was a decentralized network of people, routes, and safe places.", "Free Black communities, formerly enslaved people, and allies assisted escape despite severe legal danger; it was neither underground nor a railroad.", 2, "civilwar", ["The Underground Railroad"]),
    f("expansion-kansas-nebraska", "Expansion & Civil War", "Which 1854 law let settlers in two territories vote on slavery and effectively repealed the Missouri Compromise line?", "Kansas-Nebraska Act", ["Homestead Act", "Fugitive Slave Act", "Dawes Act"], "The Kansas-Nebraska Act applied popular sovereignty to Kansas and Nebraska.", "Its passage triggered violent conflict in Kansas and accelerated the collapse and realignment of national political parties.", 3, "civilwar"),
    f("expansion-emancipation", "Expansion & Civil War", "Which wartime order declared enslaved people free in areas still in rebellion on January 1, 1863?", "Emancipation Proclamation", ["Gettysburg Address", "Reconstruction Act", "Compromise of 1877"], "The Emancipation Proclamation made ending slavery an explicit Union war aim.", "Its immediate legal reach was limited, but it encouraged escape, authorized Black military service, and transformed the war's meaning.", 3, "civilwar", ["The Emancipation Proclamation"]),
    f("expansion-fourteenth", "Expansion & Civil War", "Which amendment established birthright citizenship and equal protection under law?", "Fourteenth Amendment", ["Thirteenth Amendment", "Fifteenth Amendment", "Nineteenth Amendment"], "The Fourteenth Amendment constitutionalized national citizenship and equal protection.", "Ratified during Reconstruction, it also includes due process and became central to later litigation over civil rights and liberties.", 4, "civilwar", ["14th Amendment", "Amendment XIV"]),

    f("industry-assembly", "Industrial & Progressive Era", "Which automobile manufacturer became closely associated with the moving assembly line?", "Ford", ["Packard", "Studebaker", "Oldsmobile"], "Ford Motor Company used moving assembly lines to reduce Model T production time and cost.", "The technique built on earlier industrial methods but demonstrated the enormous scale possible through standardized parts and tightly sequenced work.", 2, "industry", ["Henry Ford", "Ford Motor Company"]),
    f("industry-promontory", "Industrial & Progressive Era", "Where did the Union Pacific and Central Pacific railroads meet in 1869?", "Promontory Summit", ["South Pass", "Donner Pass", "Cumberland Gap"], "The first transcontinental railroad was ceremonially joined at Promontory Summit, Utah Territory.", "The connection shortened cross-country travel while relying heavily on immigrant labor and accelerating settlement and Indigenous dispossession.", 3, "industry", ["Promontory Point", "Promontory Utah"]),
    f("industry-sherman", "Industrial & Progressive Era", "Which 1890 federal law targeted combinations that restrained interstate trade?", "Sherman Antitrust Act", ["Pendleton Act", "Morrill Act", "Volstead Act"], "The Sherman Antitrust Act created a federal tool against monopolistic restraints of trade.", "Early enforcement was inconsistent and sometimes used against unions, but later cases expanded its role in competition policy.", 3, "industry", ["Sherman Act"]),
    f("industry-pullman", "Industrial & Progressive Era", "Which 1894 railroad strike began in a company town near Chicago and disrupted national rail traffic?", "Pullman Strike", ["Homestead Strike", "Haymarket Affair", "Ludlow Massacre"], "The Pullman Strike grew from wage cuts and high company-town rents.", "Federal intervention and an injunction broke the American Railway Union strike, exposing the era's intense conflict over labor and corporate power.", 4, "industry", ["The Pullman Strike"]),
    f("industry-niagara", "Industrial & Progressive Era", "Which civil-rights organization founded by W. E. B. Du Bois and others in 1905 demanded immediate equality?", "Niagara Movement", ["Grange", "Mugwumps", "Know-Nothings"], "The Niagara Movement rejected gradual accommodation and demanded full civil and political rights.", "Although short-lived, it helped supply leaders and ideas for the NAACP, founded several years later.", 5, "industry", ["The Niagara Movement"]),

    f("immigration-ellis", "Immigration & Society", "Which New York Harbor station processed millions of arriving immigrants from 1892 to 1954?", "Ellis Island", ["Angel Island", "Governors Island", "Liberty Island"], "Ellis Island became the busiest federal immigration inspection station.", "Most arrivals passed through in hours, while some faced medical examination, legal hearings, detention, or exclusion.", 2, "immigration"),
    f("immigration-chinese-exclusion", "Immigration & Society", "Which 1882 law broadly suspended immigration of Chinese laborers?", "Chinese Exclusion Act", ["Dawes Act", "Mann Act", "Burlingame Treaty"], "The Chinese Exclusion Act was the first major federal law to bar immigration by nationality and class.", "It intensified discrimination, divided families, and shaped later exclusion systems before repeal during World War II.", 3, "immigration", ["Chinese Exclusion Act of 1882"]),
    f("immigration-great-migration", "Immigration & Society", "What movement carried millions of Black Americans from the rural South to northern and western cities?", "Great Migration", ["Dust Bowl migration", "Trail of Tears", "Back-to-Africa movement"], "The Great Migration reshaped American cities, politics, labor, music, and culture.", "People sought industrial jobs and greater freedom while escaping Jim Crow violence, disfranchisement, and agricultural exploitation.", 3, "immigration", ["The Great Migration"]),
    f("immigration-gentlemens", "Immigration & Society", "Which informal 1907–1908 arrangement limited Japanese labor immigration without a formal exclusion law?", "Gentlemen's Agreement", ["Open Door Policy", "Root-Takahira Agreement", "Lansing-Ishii Agreement"], "Japan restricted passports for laborers while the United States avoided a statutory ban.", "The arrangement reflected diplomatic compromise amid intense anti-Asian discrimination, especially on the West Coast.", 4, "immigration", ["Gentlemen's Agreement of 1907"]),
    f("immigration-1924", "Immigration & Society", "Which law established national-origins quotas that strongly favored northern and western Europe?", "Immigration Act of 1924", ["Homestead Act", "Refugee Act of 1980", "Civil Rights Act of 1875"], "The Immigration Act of 1924 sharply restricted entry through discriminatory national-origins quotas.", "It also excluded immigrants ineligible for citizenship, effectively barring most immigration from Asia until later reforms.", 5, "immigration", ["Johnson-Reed Act", "1924 Immigration Act"]),

    f("rights-brown", "Civil Rights", "Which Supreme Court decision ruled that segregated public schools were inherently unequal?", "Brown v. Board of Education", ["Plessy v. Ferguson", "Korematsu v. United States", "Schenck v. United States"], "Brown v. Board rejected school segregation under the Equal Protection Clause.", "The 1954 ruling overturned the public-school application of separate but equal, though implementation faced organized resistance.", 2, "rights", ["Brown versus Board of Education", "Brown"]),
    f("rights-montgomery", "Civil Rights", "Which protest began after Rosa Parks was arrested for refusing to surrender her bus seat?", "Montgomery Bus Boycott", ["March on Washington", "Freedom Summer", "Selma campaign"], "The Montgomery Bus Boycott challenged segregated public transportation for more than a year.", "Black residents organized carpools and sustained collective action until federal courts struck down bus segregation.", 3, "rights", ["Montgomery boycott"]),
    f("rights-sit-ins", "Civil Rights", "What nonviolent tactic brought students to segregated lunch counters where they requested service and remained seated?", "Sit-ins", ["Freedom schools", "Court packing", "Rent strikes"], "Lunch-counter sit-ins exposed segregation through disciplined nonviolent protest.", "The Greensboro action of 1960 inspired rapid student organizing and helped drive desegregation across many businesses.", 3, "rights", ["Sit in protests", "Lunch counter sit-ins"]),
    f("rights-freedom-rides", "Civil Rights", "What 1961 campaign tested federal rulings against segregation in interstate bus travel?", "Freedom Rides", ["Poor People's Campaign", "Albany Movement", "Double V campaign"], "Interracial Freedom Riders traveled through the South and faced violent attacks and arrests.", "The campaign pressured federal regulators to enforce desegregation in interstate buses and terminal facilities.", 4, "rights", ["The Freedom Rides"]),
    f("rights-mfdp", "Civil Rights", "Which integrated political group challenged Mississippi's all-white Democratic delegation at the 1964 national convention?", "Mississippi Freedom Democratic Party", ["Student Nonviolent Coordinating Committee", "Congress of Racial Equality", "Southern Christian Leadership Conference"], "The Mississippi Freedom Democratic Party exposed systematic exclusion from the state's regular party.", "Fannie Lou Hamer's nationally televised testimony made the challenge a defining confrontation over representation and voting rights.", 5, "rights", ["MFDP", "Freedom Democratic Party"]),

    f("foreign-monroe", "Foreign Policy", "Which doctrine warned European powers against new colonization in the Americas?", "Monroe Doctrine", ["Truman Doctrine", "Open Door Policy", "Roosevelt Corollary"], "The Monroe Doctrine declared the Western Hemisphere closed to new European colonization.", "The United States initially lacked power to enforce the 1823 declaration alone, but later leaders expanded its meaning.", 2, "foreign", ["The Monroe Doctrine"]),
    f("foreign-marshall", "Foreign Policy", "What U.S. program funded European economic recovery after World War II?", "Marshall Plan", ["Dawes Plan", "Point Four Program", "Lend-Lease"], "The Marshall Plan supplied large-scale aid for European reconstruction.", "It sought economic recovery, trade stability, political resilience, and reduced appeal of communist movements.", 3, "foreign", ["European Recovery Program"]),
    f("foreign-cuban-missile", "Foreign Policy", "Which 1962 confrontation brought the United States and Soviet Union closest to nuclear war?", "Cuban Missile Crisis", ["Berlin Airlift", "Suez Crisis", "U-2 incident"], "The Cuban Missile Crisis centered on Soviet nuclear missiles placed in Cuba.", "A naval quarantine and secret negotiations ended the standoff, followed by removal of Soviet missiles and later U.S. missiles from Turkey.", 3, "foreign", ["October Crisis", "Caribbean Crisis"]),
    f("foreign-containment", "Foreign Policy", "What Cold War strategy sought to prevent communism from spreading to additional countries?", "Containment", ["Isolationism", "Appeasement", "Dollar diplomacy"], "Containment aimed to limit further expansion of Soviet influence and communist governments.", "It shaped alliances, aid programs, covert operations, and wars, though policymakers disagreed sharply over its application.", 4, "foreign"),
    f("foreign-open-door", "Foreign Policy", "Which policy notes called for equal commercial access to China and preservation of its territorial integrity?", "Open Door Policy", ["Good Neighbor Policy", "Big Stick policy", "Dollar diplomacy"], "The Open Door notes asked imperial powers to preserve equal trading opportunities in China.", "Issued by Secretary of State John Hay, they reflected U.S. commercial interests despite lacking formal acceptance by every recipient.", 5, "foreign", ["Open Door Notes", "Open Door"]),

    f("culture-telegraph", "Culture & Innovation", "Who developed the best-known American telegraph system and the code bearing his name?", "Samuel Morse", ["Alexander Bell", "Thomas Edison", "Eli Whitney"], "Samuel Morse helped develop a practical electrical telegraph and Morse code.", "Telegraph networks separated communication speed from transportation speed, transforming news, business, railroads, and government.", 2, "culture", ["Samuel F. B. Morse", "Morse"]),
    f("culture-harlem", "Culture & Innovation", "What cultural flowering of Black literature, music, and art centered in New York during the 1920s?", "Harlem Renaissance", ["Lost Generation", "Hudson River School", "Beat Generation"], "The Harlem Renaissance amplified diverse Black artistic and intellectual voices.", "Writers, musicians, performers, and thinkers reshaped American culture amid migration, urban life, racial pride, and continuing discrimination.", 3, "culture", ["The Harlem Renaissance"]),
    f("culture-wpa", "Culture & Innovation", "Which New Deal agency employed millions on public works and cultural projects?", "Works Progress Administration", ["Federal Reserve", "Interstate Commerce Commission", "Tennessee Valley Authority"], "The Works Progress Administration built infrastructure and supported artists, writers, musicians, and historians.", "Its projects included roads, schools, parks, murals, theater, guidebooks, and interviews preserving formerly enslaved people's recollections.", 3, "culture", ["WPA", "Work Projects Administration"]),
    f("culture-gi-bill", "Culture & Innovation", "Which 1944 law funded education and housing benefits for many returning veterans?", "GI Bill", ["Social Security Act", "Taft-Hartley Act", "National Defense Education Act"], "The GI Bill expanded access to college, training, mortgages, and business support.", "Its benefits helped grow the postwar middle class but discriminatory implementation often limited access for Black veterans.", 4, "culture", ["Servicemen's Readjustment Act"]),
    f("culture-arpanet", "Culture & Innovation", "What two-letter fragment was transmitted before the first ARPANET login attempt crashed?", "LO", ["OK", "HI", "GO"], "The first ARPANET message was intended to be LOGIN, but the system failed after LO.", "The 1969 exchange between UCLA and Stanford Research Institute became a celebrated milestone in packet-switched networking and Internet history.", 5, "culture"),
  ],
};

export default pack;
