const f = (id, subtopic, prompt, answer, distractors, explanation, details, difficulty, source, aliases = []) => ({ id, subtopics: [subtopic], prompt, answer, aliases, distractors, explanation, details, difficulty, source });

const pack = {
  packSlug: "ancient-worlds", topicSlug: "history",
  sources: {
    mesopotamia: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/3-2-ancient-mesopotamia" },
    egypt: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/3-3-ancient-egypt" },
    greece: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/6-2-ancient-greece" },
    rome: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/6-4-the-roman-republic" },
    persia: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/4-3-the-persian-empire" },
    india: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/5-4-vedic-india-to-the-fall-of-the-maurya-empire" },
    china: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/5-1-ancient-china" },
    africa: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/10-introduction" },
    americas: { label: "OpenStax World History Volume 1", url: "https://openstax.org/books/world-history-volume-1/pages/8-introduction" },
    archaeology: { label: "Smithsonian National Museum of Natural History", url: "https://naturalhistory.si.edu/education/teaching-resources/anthropology-and-social-studies/archaeology" },
  },
  facts: [
    f("mesopotamia-cuneiform", "Mesopotamia", "What wedge-shaped writing system developed in ancient Mesopotamia?", "Cuneiform", ["Hieroglyphics", "Linear B", "Runes"], "Cuneiform signs were impressed into clay with a wedge-shaped stylus.", "Sumerian scribes developed the system, and neighboring cultures later adapted it to write several different languages.", 1, "mesopotamia"),
    f("mesopotamia-ziggurat", "Mesopotamia", "What was the name of a stepped temple platform built in Mesopotamian cities?", "Ziggurat", ["Stupa", "Acropolis", "Dolmen"], "A ziggurat raised a city's principal temple on a massive stepped platform.", "These structures expressed the connection between religion and political authority and dominated many urban skylines.", 2, "mesopotamia"),
    f("mesopotamia-city-states", "Mesopotamia", "Early Sumer was organized primarily into what kind of independent political units?", "City-states", ["Nation-states", "Nomadic confederacies", "Federal republics"], "Sumer consisted of city-states such as Uruk, Ur, and Lagash.", "Each city controlled surrounding farmland and had its own rulers, temples, patron deities, and rivalries with neighboring cities.", 3, "mesopotamia"),
    f("mesopotamia-base-sixty", "Mesopotamia", "The Mesopotamian base-60 number system still influences how we divide what everyday quantities?", "Hours and angles", ["Currency and mass", "Temperature and color", "Alphabet and music"], "Base-60 mathematics survives in 60-minute hours and 360-degree circles.", "Sixty has many divisors, making common fractions convenient for astronomers, surveyors, merchants, and later mathematical traditions.", 3, "mesopotamia", ["Time and angles", "Minutes and degrees"]),
    f("mesopotamia-enheduanna", "Mesopotamia", "Which Akkadian priestess is often described as the earliest known author identified by name?", "Enheduanna", ["Sappho", "Nefertiti", "Hypatia"], "Enheduanna composed hymns while serving as high priestess of the moon god at Ur.", "Her surviving works and named authorship make her an exceptional figure in the literary history of the third millennium BCE.", 4, "mesopotamia"),

    f("egypt-nile", "Ancient Egypt", "Which river sustained ancient Egyptian agriculture through its seasonal flooding?", "Nile", ["Tigris", "Indus", "Danube"], "The Nile supplied water, fertile silt, transportation, and a geographic spine for Egypt.", "Its regular flood cycle supported intensive farming and helped bind settlements along a narrow river valley.", 1, "egypt", ["Nile River"]),
    f("egypt-hieroglyphs", "Ancient Egypt", "What name is given to ancient Egypt's formal picture-based writing system?", "Hieroglyphs", ["Cuneiform", "Ogham", "Hangul"], "Egyptian hieroglyphs combined sound signs, word signs, and meaning markers.", "Scribes also used more cursive scripts for routine documents, while hieroglyphs remained prominent on monuments and sacred texts.", 2, "egypt", ["Hieroglyphics", "Egyptian hieroglyphs"]),
    f("egypt-rosetta", "Ancient Egypt", "Which artifact carried the same decree in Greek, demotic, and hieroglyphic scripts?", "Rosetta Stone", ["Narmer Palette", "Book of the Dead", "Cyrus Cylinder"], "The Rosetta Stone gave scholars parallel versions of one text.", "Knowledge of ancient Greek helped Jean-François Champollion and others unlock the phonetic and symbolic workings of Egyptian hieroglyphs.", 3, "egypt", ["The Rosetta Stone"]),
    f("egypt-pharaoh", "Ancient Egypt", "What title is conventionally used for the ruler of ancient Egypt?", "Pharaoh", ["Archon", "Satrap", "Consul"], "Pharaohs combined political authority with a sacred role in maintaining cosmic order.", "The modern title derives from an Egyptian expression for the royal palace that later became a way to refer to the ruler.", 3, "egypt"),
    f("egypt-amarna", "Ancient Egypt", "Which pharaoh promoted the Aten and moved the royal court to a new capital at Amarna?", "Akhenaten", ["Thutmose III", "Ramesses II", "Khufu"], "Akhenaten elevated worship of the solar Aten and founded Akhetaten at modern Amarna.", "After his death, successors restored older cults, abandoned the new capital, and attempted to erase parts of his religious program.", 4, "egypt", ["Amenhotep IV"]),

    f("greece-polis", "Ancient Greece", "What Greek term means an independent city-state and its surrounding territory?", "Polis", ["Forum", "Satrapy", "Nome"], "A polis was the central political community of ancient Greek life.", "Athens, Sparta, Corinth, and Thebes developed distinct institutions and identities despite sharing language and religious traditions.", 1, "greece", ["City-state", "Greek polis"]),
    f("greece-olympia", "Ancient Greece", "At which sanctuary were the ancient Olympic Games held?", "Olympia", ["Delphi", "Delos", "Corinth"], "The Olympic Games were held at Olympia in honor of Zeus.", "Competitors and spectators traveled from across the Greek world, and a sacred truce helped make the festival possible.", 2, "greece"),
    f("greece-socratic", "Ancient Greece", "What teaching approach uses disciplined questioning to test assumptions and clarify ideas?", "Socratic method", ["Epic cycle", "Stoic exercise", "Attic measure"], "The Socratic method advances inquiry through probing questions and answers.", "Plato's dialogues portray Socrates exposing contradictions and encouraging people to examine definitions, evidence, and ethical beliefs.", 3, "greece", ["Socratic questioning"]),
    f("greece-helots", "Ancient Greece", "What name did Spartans give the state-controlled agricultural population forced to support them?", "Helots", ["Metics", "Ephors", "Hoplitai"], "Helots worked the land and supplied much of Sparta's economic base.", "Fear of revolt shaped Spartan military organization and contributed to the intense training expected of citizen soldiers.", 3, "greece", ["Helot"]),
    f("greece-ostracism", "Ancient Greece", "In classical Athens, what procedure could exile a citizen for ten years by popular vote?", "Ostracism", ["Manumission", "Proscription", "Intercalation"], "Ostracism allowed Athenians to remove a potentially dangerous political figure without confiscating property.", "Citizens scratched names onto pottery fragments called ostraka; the institution was used only during part of the fifth century BCE.", 4, "greece"),

    f("rome-republic", "Ancient Rome", "What form of government preceded imperial rule in ancient Rome?", "Republic", ["Theocracy", "Caliphate", "Feudal monarchy"], "Rome was governed as a republic before Augustus established the principate.", "Its assemblies, magistrates, and Senate distributed authority unevenly and evolved through long conflict between social orders.", 1, "rome", ["Roman Republic"]),
    f("rome-aqueduct", "Ancient Rome", "What structures carried water over long distances into Roman cities?", "Aqueducts", ["Ziggurats", "Longhouses", "Causeways"], "Roman aqueducts used carefully graded channels to move water mainly by gravity.", "Arched bridges are the most visible portions, but much of an aqueduct's route often ran underground or at ground level.", 2, "rome", ["Aqueduct"]),
    f("rome-twelve-tables", "Ancient Rome", "What was the early written foundation of Roman law displayed in the mid-fifth century BCE?", "Twelve Tables", ["Code of Justinian", "Edict of Milan", "Lex Salica"], "The Twelve Tables publicly recorded rules governing Roman civic life.", "Their publication was an important plebeian demand because it limited elite control over knowledge of legal procedures.", 3, "rome", ["The Twelve Tables", "Law of the Twelve Tables"]),
    f("rome-cursus-honorum", "Ancient Rome", "What Latin term describes the customary sequence of public offices pursued by Roman politicians?", "Cursus honorum", ["Pax deorum", "Mos maiorum", "Panem et circenses"], "The cursus honorum organized advancement through offices such as quaestor, praetor, and consul.", "Age requirements, intervals, and prior service helped structure elite competition, though powerful figures sometimes bent the rules.", 3, "rome"),
    f("rome-tetrarchy", "Ancient Rome", "Which emperor created the Tetrarchy, dividing senior imperial rule among four leaders?", "Diocletian", ["Trajan", "Hadrian", "Vespasian"], "Diocletian introduced the Tetrarchy to manage the empire's military and succession crises.", "Two senior Augusti and two junior Caesars governed different regions, though the system fractured after Diocletian retired.", 4, "rome"),

    f("persia-cyrus", "Ancient Persia", "Who founded the Achaemenid Persian Empire?", "Cyrus the Great", ["Xerxes I", "Darius III", "Artaxerxes II"], "Cyrus the Great united Persian power and conquered a vast Near Eastern empire.", "His successors expanded and administered a realm stretching from the Indus Valley toward the Mediterranean and Egypt.", 1, "persia", ["Cyrus II", "Cyrus"]),
    f("persia-royal-road", "Ancient Persia", "What major route linked Susa with Sardis and supported Achaemenid administration?", "Royal Road", ["Appian Way", "Amber Road", "Incense Route"], "The Royal Road connected important centers of the Persian Empire.", "Relay stations and protected routes allowed messages, officials, troops, and goods to move more reliably across great distances.", 2, "persia", ["Persian Royal Road"]),
    f("persia-zoroastrian", "Ancient Persia", "In Zoroastrian tradition, what is the name of the supreme wise deity?", "Ahura Mazda", ["Marduk", "Amun-Ra", "Baal"], "Ahura Mazda is the wise lord at the center of Zoroastrian belief.", "The tradition emphasizes truth, moral choice, and conflict between forces of order and destructive falsehood.", 3, "persia"),
    f("persia-qanat", "Ancient Persia", "What underground channel system carried groundwater to dry settlements and fields in ancient Iran?", "Qanat", ["Aqueduct bridge", "Chinampa", "Nilometer"], "A qanat uses a gently sloping tunnel to bring groundwater to the surface by gravity.", "Vertical shafts allowed construction and maintenance while the underground route reduced evaporation in arid climates.", 3, "persia", ["Qanats", "Kariz"]),
    f("persia-kings-eyes", "Ancient Persia", "What nickname was given to royal inspectors who reported on Persian provincial officials?", "The King's Eyes and Ears", ["The Bronze Guard", "The Sacred Band", "The Ten Thousand"], "Royal inspectors were known as the King's Eyes and Ears.", "Their independent reports helped the monarch monitor satraps and other officials across an empire too large for constant direct supervision.", 4, "persia", ["King's Eyes and Ears", "Eyes and Ears of the King"]),

    f("india-indus-cities", "Ancient South Asia", "Harappa and Mohenjo-daro belonged to which Bronze Age civilization?", "Indus Valley civilization", ["Minoan civilization", "Olmec civilization", "Nok culture"], "Harappa and Mohenjo-daro were major cities of the Indus Valley civilization.", "Their planned streets, drainage systems, standardized weights, and extensive trade indicate sophisticated urban administration.", 2, "india", ["Harappan civilization", "Indus civilization"]),
    f("india-vedas", "Ancient South Asia", "In which ancient language were the Vedas composed?", "Sanskrit", ["Tamil", "Pali", "Avestan"], "The Vedas were preserved in an early form of Sanskrit through precise oral transmission.", "These collections of hymns and ritual knowledge became foundational texts for later Hindu traditions.", 3, "india", ["Vedic Sanskrit"]),
    f("india-ashoka-edicts", "Ancient South Asia", "On what durable objects did Ashoka famously publish moral and administrative edicts?", "Rocks and pillars", ["Papyrus scrolls", "Silk banners", "Wooden tablets only"], "Ashoka had edicts carved on rock faces and monumental pillars across his empire.", "Their different languages and scripts communicated policies, moral guidance, and the ruler's concern for welfare to diverse populations.", 3, "india", ["Stone pillars and rocks", "Pillars and rock faces"]),
    f("india-gupta-zero", "Ancient South Asia", "Which mathematical concept was developed into a number with place-value use by Indian mathematicians?", "Zero", ["Imaginary unit", "Roman numeral V", "Golden ratio"], "Indian mathematicians made zero a number and place-value marker within a decimal system.", "Their notation and arithmetic methods spread through the Islamic world and eventually became fundamental to global mathematics.", 4, "india", ["The number zero"]),
    f("india-arthashastra", "Ancient South Asia", "Which Sanskrit treatise traditionally attributed to Kautilya discusses government, diplomacy, and statecraft?", "Arthashastra", ["Mahabharata", "Upanishads", "Ramcharitmanas"], "The Arthashastra is a systematic work on rulership, administration, economics, intelligence, and war.", "Its surviving text reflects several periods of composition, but tradition associates it with Chandragupta Maurya's adviser Kautilya.", 5, "india", ["Arthaśāstra"]),

    f("china-yellow-river", "Ancient China", "Which river is also known as the Huang He?", "Yellow River", ["Yangtze River", "Pearl River", "Mekong River"], "Huang He means Yellow River, named for the sediment carried in its water.", "The river supported early northern Chinese states but its changing course and catastrophic floods also caused repeated destruction.", 2, "china", ["Huang He"]),
    f("china-oracle-bones", "Ancient China", "Shang diviners inscribed questions on what objects before heating and interpreting cracks?", "Oracle bones", ["Papyrus rolls", "Clay bullae", "Wax tablets"], "Oracle bones were usually turtle plastrons or animal shoulder blades used in royal divination.", "Their inscriptions preserve the earliest substantial body of Chinese writing and evidence about Shang rulers and concerns.", 3, "china", ["Oracle bone"]),
    f("china-mandate", "Ancient China", "What doctrine held that a Chinese dynasty's right to rule depended on moral order?", "Mandate of Heaven", ["Divine right of kings", "Social contract", "Pax Sinica"], "The Mandate of Heaven justified rule but allowed that an unjust dynasty could lose legitimacy.", "Rebellion, disaster, and disorder could be interpreted as signs that Heaven had transferred the mandate to a new house.", 3, "china", ["Heaven's mandate"]),
    f("china-terracotta", "Ancient China", "The Terracotta Army was buried to guard the tomb of which ruler?", "Qin Shi Huang", ["Emperor Wu", "Kublai Khan", "Hongwu Emperor"], "Thousands of terracotta figures accompanied China's first emperor in his vast burial complex.", "The individually modeled soldiers, horses, and chariots reflected imperial power and beliefs about protection in the afterlife.", 4, "china", ["Qin Shihuangdi", "First Emperor of Qin"]),
    f("china-zhang-qian", "Ancient China", "Which Han envoy's journeys helped open sustained Chinese contact with Central Asia?", "Zhang Qian", ["Sima Qian", "Zheng He", "Ban Zhao"], "Zhang Qian returned with valuable knowledge of Central Asian peoples, routes, and goods.", "His missions encouraged Han diplomacy and expansion and helped develop the exchange networks later called the Silk Roads.", 5, "china"),

    f("africa-aksum-stelae", "Ancient Africa", "Which African kingdom is famous for monumental stone stelae at its capital in Ethiopia?", "Aksum", ["Carthage", "Ghana", "Benin"], "Aksumite rulers raised monumental stone stelae over elite burial areas.", "The kingdom prospered through Red Sea trade, minted coins, and adopted Christianity during the fourth century.", 2, "africa", ["Axum", "Kingdom of Aksum"]),
    f("africa-nok", "Ancient Africa", "Which ancient culture of present-day Nigeria is known for distinctive terracotta figures?", "Nok culture", ["Moche culture", "Hallstatt culture", "Jomon culture"], "Nok sites produced expressive terracotta heads and figures in the first millennium BCE and later.", "Archaeological evidence also connects Nok communities with farming and early ironworking in West Africa.", 3, "africa", ["Nok"]),
    f("africa-meroe", "Ancient Africa", "Meroe became a major capital of which Nile Valley kingdom south of Egypt?", "Kush", ["Aksum", "Numidia", "Songhai"], "Meroe was a political and industrial center of the Kingdom of Kush.", "Its rulers built pyramids, developed a distinctive script, and participated in trade linking inner Africa with Egypt and the Red Sea.", 3, "africa", ["Kingdom of Kush", "Kushite kingdom"]),
    f("africa-bantu", "Ancient Africa", "What broad migration spread related languages, farming, and ironworking across much of sub-Saharan Africa?", "Bantu expansion", ["Sea Peoples migration", "Dorian invasion", "Great Trek"], "The Bantu expansion was a long, complex movement of communities rather than one campaign.", "Over many centuries, Bantu-speaking peoples interacted with existing populations and transformed the linguistic and agricultural map of Africa.", 4, "africa", ["Bantu migrations", "Bantu migration"]),
    f("africa-periplus", "Ancient Africa", "Which Greco-Roman sailing guide describes Red Sea and Indian Ocean ports including East African trade centers?", "Periplus of the Erythraean Sea", ["Tabula Peutingeriana", "Book of the Dead", "Antonine Itinerary"], "The Periplus of the Erythraean Sea records routes, ports, rulers, and traded goods around the western Indian Ocean.", "Written in Greek during the first century CE, it provides rare evidence about commerce linking Roman Egypt, Arabia, India, and East Africa.", 5, "africa", ["Periplus Maris Erythraei", "Erythraean Sea Periplus"]),

    f("americas-maya-writing", "Ancient Americas", "Which Mesoamerican civilization developed the most fully deciphered writing system in the pre-Columbian Americas?", "Maya", ["Inca", "Mississippian", "Norte Chico"], "Maya writing combined signs for words and syllables.", "Inscriptions on monuments, ceramics, and books recorded dynastic history, ritual, astronomy, and political events.", 2, "americas", ["Maya civilization", "The Maya"]),
    f("americas-olmec-heads", "Ancient Americas", "Which early Mesoamerican culture carved colossal basalt heads?", "Olmec", ["Toltec", "Zapotec", "Inca"], "The Olmec carved massive stone heads portraying helmeted individuals, probably rulers.", "Transporting basalt over long distances required extensive labor and organization at centers such as San Lorenzo and La Venta.", 3, "americas", ["Olmec culture"]),
    f("americas-chinampas", "Ancient Americas", "What name is given to the highly productive raised fields built in shallow lakes by central Mexican farmers?", "Chinampas", ["Qanats", "Terraces", "Kivas"], "Chinampas were rectangular planting areas built from lake mud and organic material.", "Canals provided transport and moisture, supporting intensive agriculture around cities including Tenochtitlan.", 3, "americas", ["Chinampa"]),
    f("americas-nazca", "Ancient Americas", "Which culture created enormous geoglyphs on the desert floor of southern Peru?", "Nazca", ["Maya", "Adena", "Chimu"], "The Nazca Lines include straight paths, geometric forms, and figures of animals and plants.", "Their dry environment preserved shallow designs made by removing dark surface stones to expose lighter ground beneath.", 4, "americas", ["Nasca", "Nazca culture"]),
    f("americas-moche-portraits", "Ancient Americas", "Which ancient Peruvian culture is especially known for realistic ceramic portrait vessels?", "Moche", ["Hopewell", "Olmec", "Taíno"], "Moche potters created modeled vessels portraying individuals with remarkable facial detail.", "Their ceramics also depict warfare, ritual, craft production, animals, and daily life on Peru's northern coast.", 5, "americas", ["Moche culture", "Mochica"]),

    f("archaeology-artifact", "Archaeology", "What is a portable object made or modified by humans called in archaeology?", "Artifact", ["Ecofact", "Stratum", "Fossil species"], "An artifact is material culture shaped or used by people.", "Tools, pottery, ornaments, and coins can reveal technology, exchange, identity, chronology, and everyday activity.", 2, "archaeology", ["Artefact"]),
    f("archaeology-stratigraphy", "Archaeology", "What method studies the order and relationship of archaeological soil layers?", "Stratigraphy", ["Ethnography", "Numismatics", "Paleography"], "Stratigraphy reconstructs the sequence in which deposits accumulated or were disturbed.", "In an undisturbed site, deeper layers are generally older, but pits, erosion, rebuilding, and animal activity can complicate the sequence.", 3, "archaeology"),
    f("archaeology-radiocarbon", "Archaeology", "Which dating method measures the decay of carbon-14 in once-living material?", "Radiocarbon dating", ["Potassium-argon dating", "Dendrochronology", "Seriation"], "Radiocarbon dating estimates when an organism stopped exchanging carbon with its environment.", "Calibration against tree rings and other records converts measured radiocarbon ages into more accurate calendar ranges.", 3, "archaeology", ["Carbon-14 dating", "C14 dating"]),
    f("archaeology-tree-rings", "Archaeology", "What dating method matches patterns of annual tree growth rings?", "Dendrochronology", ["Thermoluminescence", "Palynology", "Epigraphy"], "Dendrochronology can date wood by matching its ring-width pattern to established sequences.", "Where long regional chronologies exist, the method may identify the exact calendar year in which a tree ring formed.", 4, "archaeology", ["Tree-ring dating"]),
    f("archaeology-thermoluminescence", "Archaeology", "Which technique dates fired pottery by measuring light released from trapped energy when reheated?", "Thermoluminescence dating", ["Radiocarbon dating", "Obsidian hydration", "Tree-ring dating"], "Thermoluminescence estimates time since a mineral was strongly heated and its stored signal reset.", "Radiation gradually traps electrons in crystal defects; laboratory heating releases energy as light proportional to accumulated exposure.", 5, "archaeology", ["Thermoluminescence", "TL dating"]),
  ],
};

export default pack;
