const f = (id, subtopic, prompt, answer, distractors, explanation, details, difficulty, source, aliases = []) => ({ id, subtopics: [subtopic], prompt, answer, aliases, distractors, explanation, details, difficulty, source });

const pack = {
  packSlug: "wild-world",
  topicSlug: "science-nature",
  sources: {
    evolution: { label: "OpenStax Biology 2e", url: "https://openstax.org/books/biology-2e/pages/18-introduction" },
    ecology: { label: "OpenStax Biology 2e", url: "https://openstax.org/books/biology-2e/pages/44-introduction" },
    mammals: { label: "Smithsonian National Museum of Natural History", url: "https://naturalhistory.si.edu/education/teaching-resources/anthropology-and-social-studies/human-evolution" },
    birds: { label: "Cornell Lab of Ornithology", url: "https://www.allaboutbirds.org/news/bird-academy/all-about-bird-anatomy/" },
    marine: { label: "NOAA Ocean Service", url: "https://oceanservice.noaa.gov/facts/" },
    plants: { label: "OpenStax Biology 2e", url: "https://openstax.org/books/biology-2e/pages/30-introduction" },
    insects: { label: "Smithsonian National Museum of Natural History", url: "https://naturalhistory.si.edu/education/teaching-resources/anthropology-and-social-studies/insects" },
    conservation: { label: "IUCN", url: "https://www.iucnredlist.org/about/background-history" },
    herps: { label: "National Park Service", url: "https://www.nps.gov/subjects/nnlandmarks/reptiles-and-amphibians.htm" },
    habitats: { label: "National Geographic Society", url: "https://education.nationalgeographic.org/resource/biome/" },
  },
  facts: [
    f("evolution-natural-selection", "Evolution", "What process favors inherited traits that improve reproductive success?", "Natural selection", ["Genetic engineering", "Artificial classification", "Ecological succession"], "Natural selection changes populations when heritable traits affect reproductive success.", "Individuals do not evolve because they need to; over generations, variants that leave more offspring become more common in a population.", 1, "evolution"),
    f("evolution-common-ancestor", "Evolution", "Structures inherited from a shared ancestor, such as a whale flipper and a human arm, are called what?", "Homologous structures", ["Vestigial organs", "Analogous structures", "Clonal traits"], "Homologous structures share an underlying anatomy inherited from a common ancestor.", "They may serve different functions after lineages diverge, unlike analogous structures that evolved independently under similar selective pressures.", 2, "evolution", ["Homologies", "Homologous traits"]),
    f("evolution-founder-effect", "Evolution", "What form of genetic drift occurs when a new population begins with only a few individuals?", "Founder effect", ["Gene flow", "Stabilizing selection", "Hybrid vigor"], "The founder effect produces unusual allele frequencies in a population established by a small group.", "Because the founders carry only part of the original population's variation, rare traits may become common simply by chance.", 3, "evolution"),
    f("evolution-convergent", "Evolution", "Sharks and dolphins independently evolved streamlined bodies. What evolutionary pattern does this illustrate?", "Convergent evolution", ["Coevolution", "Divergent evolution", "Adaptive radiation"], "Convergent evolution produces similar adaptations in lineages that are not closely related.", "Comparable environmental pressures can favor similar solutions even though the underlying structures arose from different ancestors.", 4, "evolution"),
    f("evolution-hox", "Evolution", "Which highly conserved gene family helps establish the head-to-tail body plan of many animals?", "Hox genes", ["Opsin genes", "Globin genes", "Ribosomal genes"], "Hox genes help specify the identity of body regions during embryonic development.", "Their similar organization across distant animal groups provides strong evidence that major developmental mechanisms arose early in animal evolution.", 5, "evolution", ["Homeobox genes", "Hox gene family"]),

    f("ecology-food-web", "Ecology", "What diagram shows interconnected feeding relationships within an ecosystem?", "Food web", ["Cladogram", "Weather map", "Punnett square"], "A food web links the many food chains operating in an ecosystem.", "Because most species eat or are eaten by more than one organism, a web represents ecological relationships more realistically than a single chain.", 1, "ecology"),
    f("ecology-keystone", "Ecology", "What term describes a species whose ecological effect is unusually large relative to its abundance?", "Keystone species", ["Pioneer species", "Indicator fossil", "Endemic species"], "A keystone species has a disproportionate influence on community structure.", "Removing one can trigger cascading changes in populations and habitat, as famously observed with sea otters, urchins, and kelp forests.", 2, "ecology"),
    f("ecology-primary-succession", "Ecology", "Ecological succession beginning on newly exposed rock with no soil is called what?", "Primary succession", ["Secondary succession", "Seasonal migration", "Competitive exclusion"], "Primary succession starts where a biological community and developed soil are absent.", "Pioneer organisms such as lichens help weather rock and add organic matter, gradually creating conditions that support larger plants.", 3, "ecology"),
    f("ecology-trophic-cascade", "Ecology", "What is a chain of ecological changes caused by adding or removing a predator called?", "Trophic cascade", ["Founder effect", "Nutrient cycle", "Population bottleneck"], "A trophic cascade occurs when effects at one feeding level spread through others.", "Predators can indirectly alter vegetation, waterways, or habitat by changing the abundance or behavior of the herbivores they consume.", 4, "ecology"),
    f("ecology-net-primary", "Ecology", "What measure equals plant energy captured by photosynthesis minus the energy plants use in respiration?", "Net primary productivity", ["Carrying capacity", "Biomagnification", "Gross assimilation efficiency"], "Net primary productivity is the energy stored as new plant biomass after respiration.", "It represents the portion of primary production available to herbivores, decomposers, and the rest of an ecosystem's food web.", 5, "ecology", ["NPP", "Net primary production"]),

    f("mammals-milk", "Mammals", "What defining substance do mammary glands produce?", "Milk", ["Venom", "Bile", "Mucus"], "Mammary glands produce milk to nourish young mammals.", "Other common mammalian traits include hair and three middle-ear bones, although egg-laying monotremes show that not every mammal gives live birth.", 1, "mammals"),
    f("mammals-monotremes", "Mammals", "Which unusual mammal group includes the platypus and echidnas?", "Monotremes", ["Marsupials", "Rodents", "Cetaceans"], "Monotremes are mammals that lay eggs.", "They still produce milk and possess hair, placing them firmly among mammals despite their distinctive reproductive biology.", 2, "mammals"),
    f("mammals-echolocation", "Mammals", "Bats and toothed whales can navigate by interpreting returning sound echoes. What is this ability called?", "Echolocation", ["Electroreception", "Bioluminescence", "Magnetotaxis"], "Echolocation uses emitted sounds and returning echoes to detect objects.", "Timing, frequency, and intensity differences help an animal estimate a target's direction, distance, size, and sometimes movement.", 3, "mammals"),
    f("mammals-ruminant", "Mammals", "Cattle and deer repeatedly chew partially digested plant material known by what name?", "Cud", ["Chyme", "Krill", "Detritus"], "Ruminants regurgitate and rechew cud as part of digesting cellulose-rich plants.", "Microbes in specialized stomach chambers ferment plant material, releasing nutrients that the animal could not obtain efficiently by itself.", 3, "mammals"),
    f("mammals-countercurrent", "Mammals", "What heat-saving exchange system lets warm arterial blood transfer heat to colder returning blood in limbs?", "Countercurrent heat exchange", ["Evaporative cooling", "Brown-fat thermogenesis", "Vasomotor shivering"], "Countercurrent exchange conserves body heat by placing opposite blood flows close together.", "Seals, whales, and many other animals use it in extremities so tissues remain supplied while less heat escapes to cold surroundings.", 4, "mammals", ["Countercurrent exchange"]),

    f("birds-feathers", "Birds", "Which living animal group is uniquely characterized by feathers?", "Birds", ["Mammals", "Reptiles", "Insects"], "Feathers are unique to birds among living animals.", "They provide insulation, display surfaces, camouflage, waterproofing, and the aerodynamic structures needed for flight in most species.", 1, "birds", ["Aves"]),
    f("birds-keeled-sternum", "Birds", "The large flight muscles of most birds attach to a ridge on which chest bone?", "Sternum", ["Pelvis", "Clavicle", "Vertebra"], "A keel on the sternum provides a broad attachment for powerful flight muscles.", "Strong pectoral muscles drive the downstroke, while a second major muscle raises the wing through a tendon-and-pulley arrangement.", 2, "birds", ["Breastbone"]),
    f("birds-air-sacs", "Birds", "What structures keep air moving through a bird's lungs during both inhalation and exhalation?", "Air sacs", ["Swim bladders", "Crop glands", "Salt glands"], "Bird air sacs act like bellows that maintain one-way airflow through the lungs.", "This highly efficient system supports the oxygen demands of flight and differs from the tidal in-and-out ventilation of mammalian lungs.", 3, "birds"),
    f("birds-imprinting", "Birds", "What rapid early-life learning can cause a hatchling to follow the first suitable moving object it sees?", "Imprinting", ["Mimicry", "Hibernation", "Habituation"], "Imprinting is fast learning during a sensitive developmental period.", "In many waterfowl it helps young identify and follow a parent, although experimental studies showed that other moving objects can trigger it.", 3, "birds"),
    f("birds-magnetic", "Birds", "What environmental field can many migratory birds sense as a navigation cue?", "Earth's magnetic field", ["Ocean salinity", "Atmospheric ozone", "Lunar gravity alone"], "Many birds possess magnetoreception that contributes to long-distance navigation.", "They combine magnetic information with landmarks, stars, the Sun, odors, and learned routes rather than relying on a single compass.", 4, "birds", ["Geomagnetic field", "Magnetic field"]),

    f("marine-coral", "Marine Life", "Coral reefs are built primarily by colonies of what kind of animal?", "Coral polyps", ["Sea sponges", "Marine worms", "Bivalves"], "Tiny coral polyps secrete the calcium-carbonate skeletons that build reefs.", "Many reef-building corals also host photosynthetic algae that supply energy, making them sensitive to warming that can disrupt the partnership.", 1, "marine", ["Corals", "Coral"]),
    f("marine-largest", "Marine Life", "What is the largest animal known to have lived on Earth?", "Blue whale", ["Whale shark", "African elephant", "Giant squid"], "The blue whale is the largest known animal in Earth's history.", "Adults can exceed 25 meters and feed mainly on tiny krill, demonstrating that enormous body size does not require hunting large prey.", 2, "marine"),
    f("marine-upwelling", "Marine Life", "What process brings cold, nutrient-rich deep water toward the ocean surface?", "Upwelling", ["Desalination", "Thermal inversion", "Tidal locking"], "Upwelling supplies surface waters with nutrients that support plankton growth.", "Wind and Earth's rotation can move surface water away from a coast or region, allowing deeper water to rise and fuel productive fisheries.", 3, "marine"),
    f("marine-whale-shark", "Marine Life", "Despite its name and enormous size, the whale shark feeds mainly by using what method?", "Filter feeding", ["Venom injection", "Ambush constriction", "Electrocution"], "Whale sharks filter plankton and small organisms from seawater.", "They are sharks, not whales, but their gentle feeding style and great size inspired the name; they strain food using specialized structures near the gills.", 3, "marine", ["Filter feeder"]),
    f("marine-carbonate", "Marine Life", "Ocean acidification makes it harder for many organisms to build shells from which mineral?", "Calcium carbonate", ["Sodium chloride", "Silicon carbide", "Iron oxide"], "More acidic seawater reduces the carbonate ions needed to form calcium-carbonate shells and skeletons.", "Corals, mollusks, and some plankton can therefore face greater energetic costs or weakened structures as carbon dioxide enters the ocean.", 4, "marine", ["Calcite", "Aragonite"]),

    f("plants-photosynthesis", "Plant Biology", "Which green pigment absorbs light for photosynthesis?", "Chlorophyll", ["Hemoglobin", "Keratin", "Melanin"], "Chlorophyll captures light energy used in photosynthesis.", "It absorbs strongly in red and blue wavelengths while reflecting more green light, which is why many leaves appear green.", 1, "plants"),
    f("plants-xylem", "Plant Biology", "Which vascular tissue carries water and dissolved minerals upward through a plant?", "Xylem", ["Phloem", "Cambium", "Epidermis"], "Xylem conducts water and minerals from roots toward stems and leaves.", "Its conducting cells are reinforced with lignin, which also helps vascular plants stand upright against gravity.", 2, "plants"),
    f("plants-phloem", "Plant Biology", "What tissue transports sugars from leaves to growing or storage tissues?", "Phloem", ["Xylem", "Cork", "Pith"], "Phloem distributes sugars and other organic compounds between plant sources and sinks.", "Transport can move upward or downward depending on where sugars are produced and where the plant is actively growing or storing energy.", 3, "plants"),
    f("plants-tropism", "Plant Biology", "A plant shoot bending toward light demonstrates which response?", "Phototropism", ["Gravitropism", "Vernalization", "Transpiration"], "Phototropism is directional growth in response to light.", "Unequal distribution of the hormone auxin causes cells on one side of a young shoot to elongate more, curving the shoot toward illumination.", 3, "plants"),
    f("plants-cam", "Plant Biology", "Which water-saving photosynthetic strategy lets many desert plants open their stomata mainly at night?", "CAM photosynthesis", ["C3 respiration", "Photorespiration", "Nitrogen fixation"], "CAM plants take in carbon dioxide at night and use it during daytime photosynthesis.", "Separating gas intake from daylight reduces water loss, helping cacti, agaves, and other plants survive hot, dry conditions.", 4, "plants", ["Crassulacean acid metabolism", "CAM"]),

    f("insects-six-legs", "Insects", "How many legs does an adult insect have?", "6", ["4", "8", "10"], "Adult insects have three pairs of legs attached to the thorax.", "They also have a head and abdomen; spiders have eight legs and belong to arachnids rather than insects.", 1, "insects", ["Six"]),
    f("insects-metamorphosis", "Insects", "A butterfly passes through egg, larva, pupa, and adult stages. What is this life cycle called?", "Complete metamorphosis", ["Binary fission", "Alternation of generations", "Direct development"], "Complete metamorphosis separates larval, pupal, and adult body plans.", "Because larvae and adults often use different foods and habitats, the stages may compete less directly with one another.", 2, "insects", ["Holometabolous development", "Holometabolism"]),
    f("insects-pollination", "Insects", "When a bee moves pollen between flowers of the same species, what process does it enable?", "Pollination", ["Germination", "Fermentation", "Translocation"], "Pollination transfers pollen so flowering plants can reproduce sexually.", "Bees, butterflies, moths, flies, beetles, birds, bats, wind, and water all pollinate different groups of plants.", 3, "insects"),
    f("insects-eusocial", "Insects", "What term describes colonies with cooperative brood care, overlapping generations, and reproductive castes?", "Eusocial", ["Solitary", "Parasitic", "Nomadic"], "Eusocial colonies divide reproduction and other labor among specialized members.", "Many ants, termites, and some bees and wasps meet the defining criteria, with queens reproducing while workers support the colony.", 3, "insects", ["Eusociality"]),
    f("insects-halteres", "Insects", "Flies use which modified pair of wings as gyroscopic balance organs?", "Halteres", ["Elytra", "Cerci", "Spiracles"], "Halteres vibrate during flight and detect body rotation.", "These club-shaped structures evolved from the hindwings and provide rapid feedback that helps flies perform precise aerial maneuvers.", 4, "insects", ["Halter"]),

    f("conservation-endangered", "Conservation", "On the IUCN Red List, which category indicates a species faces a very high risk of extinction in the wild?", "Endangered", ["Least Concern", "Near Threatened", "Data Deficient"], "Endangered species meet criteria indicating a very high extinction risk in the wild.", "The still more severe Critically Endangered category indicates an extremely high risk; categories reflect evidence rather than legal protection by themselves.", 1, "conservation"),
    f("conservation-invasive", "Conservation", "What term describes a non-native species that spreads and causes ecological or economic harm?", "Invasive species", ["Keystone species", "Indicator species", "Pioneer species"], "An invasive species is introduced outside its native range and causes harm.", "Not every non-native organism becomes invasive; damaging species may outcompete native life, alter habitats, spread disease, or disrupt economies.", 2, "conservation", ["Invasive alien species"]),
    f("conservation-corridor", "Conservation", "What habitat connection allows wildlife to move between otherwise isolated protected areas?", "Wildlife corridor", ["Ecological trap", "Trophic pyramid", "Buffer toxin"], "Wildlife corridors connect habitat fragments and make movement safer.", "They can support migration, access to mates, seasonal resources, and gene flow, although their design must match the needs of target species.", 3, "conservation", ["Habitat corridor", "Ecological corridor"]),
    f("conservation-captive", "Conservation", "Breeding threatened animals under human care for later reintroduction is known as what?", "Captive breeding", ["Assisted migration", "Habitat banking", "Trophic rewilding"], "Captive breeding can increase numbers and preserve genetic diversity outside the wild.", "Successful programs also require suitable habitat, careful pedigree management, disease control, and preparation for survival after release.", 3, "conservation", ["Conservation breeding"]),
    f("conservation-biodiversity-hotspot", "Conservation", "What conservation term identifies a region with exceptional endemic plant diversity that has lost most of its original habitat?", "Biodiversity hotspot", ["Carbon sink", "Wildlife refuge", "Ecological niche"], "A biodiversity hotspot combines high endemism with severe habitat loss.", "The concept helps prioritize limited conservation resources toward regions holding many unique species under intense threat.", 4, "conservation"),

    f("herps-amphibian-skin", "Reptiles & Amphibians", "Why must many amphibians keep their skin moist?", "They exchange gases through it", ["It produces feathers", "It stores bone marrow", "It reflects all sunlight"], "Many amphibians supplement lung breathing with gas exchange across moist skin.", "Their permeable skin also makes them sensitive to dehydration, pollutants, and environmental change, which contributes to their value as ecological indicators.", 2, "herps", ["Cutaneous respiration", "To breathe through their skin"]),
    f("herps-ectotherm", "Reptiles & Amphibians", "Reptiles largely regulate body temperature using outside heat. What is this condition called?", "Ectothermy", ["Endothermy", "Homeostasis", "Bioluminescence"], "Ectothermic animals depend heavily on environmental heat sources.", "A lizard may bask or seek shade to control temperature, reducing metabolic energy costs but tying activity to suitable conditions.", 2, "herps", ["Ectothermic", "Cold-blooded"]),
    f("herps-amniotic", "Reptiles & Amphibians", "Which reproductive adaptation helped ancestral reptiles reproduce away from open water?", "Amniotic egg", ["External gills", "Pupal case", "Placoid scale"], "The amniotic egg provides membranes and protection for an embryo on land.", "Its compartments manage gas exchange, waste, nutrition, and cushioning; birds and mammals also belong to the amniote lineage.", 3, "herps", ["Amniote egg"]),
    f("herps-crocodilian-heart", "Reptiles & Amphibians", "Unlike most other living reptiles, crocodilians have a heart with how many chambers?", "4", ["2", "3", "5"], "Crocodilians have two atria and two fully divided ventricles.", "Special connections between major vessels still allow blood-flow adjustments during diving, giving their circulation unusual flexibility.", 3, "herps", ["Four"]),
    f("herps-neoteny", "Reptiles & Amphibians", "Axolotls retain larval features such as external gills as adults. What is this called?", "Neoteny", ["Mimicry", "Estivation", "Parthenogenesis"], "Neoteny is the retention of juvenile traits in a sexually mature animal.", "Axolotls normally mature without the complete metamorphosis seen in many salamanders, although hormones can sometimes induce transformation.", 3, "herps"),

    f("habitat-desert", "Habitats & Biomes", "Which biome is defined primarily by very low precipitation rather than temperature?", "Desert", ["Tundra", "Savanna", "Taiga"], "Deserts receive little precipitation and may be hot or cold.", "Sparse water availability shapes plant form, animal behavior, soil development, and the timing of biological activity.", 2, "habitats"),
    f("habitat-taiga", "Habitats & Biomes", "What forest biome forms a broad conifer-dominated belt across northern North America and Eurasia?", "Taiga", ["Chaparral", "Pampas", "Mangrove"], "The taiga, or boreal forest, is dominated by cold-adapted conifers.", "It lies south of tundra across high northern latitudes and stores enormous amounts of carbon in vegetation and soils.", 2, "habitats", ["Boreal forest"]),
    f("habitat-estuary", "Habitats & Biomes", "What coastal habitat forms where river freshwater mixes with seawater?", "Estuary", ["Atoll", "Abyssal plain", "Glacier"], "An estuary is a partially enclosed coastal body where fresh and salt water mix.", "Variable salinity and abundant nutrients create productive nursery habitat for fish, shellfish, birds, and other wildlife.", 3, "habitats"),
    f("habitat-mangrove", "Habitats & Biomes", "Which salt-tolerant coastal forests protect many tropical shorelines with tangled roots?", "Mangroves", ["Redwoods", "Heathlands", "Cloud forests"], "Mangroves grow in intertidal tropical and subtropical environments.", "Their roots trap sediment, reduce erosion and wave energy, store carbon, and provide nursery habitat for numerous marine species.", 3, "habitats", ["Mangrove forests"]),
    f("habitat-ecotone", "Habitats & Biomes", "What is a transition zone between two ecological communities called?", "Ecotone", ["Watershed", "Thermocline", "Monoculture"], "An ecotone contains environmental conditions and species from neighboring communities.", "Forest edges, marsh boundaries, and treelines can host distinctive interactions and sometimes unusually high species richness.", 3, "habitats"),
  ],
};

export default pack;
