import { Plus, Users } from "lucide-react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { requireUser } from "@/lib/auth";
import { createGroup } from "./actions";

export default async function GroupsPage() {
  const { user, supabase } = await requireUser();
  const { data: memberships } = await supabase.from("group_memberships").select("role,groups(id,name,description,created_at)").eq("user_id", user.id).order("joined_at", { ascending: false });
  return <><header><p className="text-sm font-black uppercase tracking-[.2em] text-[var(--brand)]">Your circles</p><h1 className="mt-2 text-4xl font-black">Groups</h1></header><section className="mt-8 grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="grid gap-4 sm:grid-cols-2">{memberships?.map((membership) => { const group = Array.isArray(membership.groups) ? membership.groups[0] : membership.groups; return group ? <Link href={`/groups/${group.id}`} key={group.id}><Card className="h-full p-6 transition hover:-translate-y-1 hover:border-emerald-300/30"><Users className="text-[var(--brand)]" /><h2 className="mt-5 text-xl font-black">{group.name}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{group.description || "A private Mindspan group."}</p><span className="mt-5 inline-block text-xs font-black uppercase tracking-wider text-emerald-200">{membership.role}</span></Card></Link> : null; })}{!memberships?.length ? <Card className="p-8 text-center sm:col-span-2"><Users className="mx-auto text-[var(--muted)]" size={40} /><h2 className="mt-5 text-xl font-black">Create your first group</h2><p className="mt-2 text-[var(--muted)]">Invite family and friends, compare specialties, and see where your knowledge overlaps.</p></Card> : null}</div><Card className="h-fit p-6"><div className="flex items-center gap-3"><Plus className="text-[var(--brand)]" /><h2 className="text-lg font-black">New group</h2></div><form action={createGroup} className="mt-5 space-y-4"><input className="min-h-12 w-full rounded-2xl border border-white/15 bg-slate-950/50 px-4" name="name" placeholder="Group name" required /><textarea className="min-h-28 w-full rounded-2xl border border-white/15 bg-slate-950/50 p-4" name="description" placeholder="What brings this group together?" /><button className="min-h-11 w-full rounded-full bg-[var(--brand)] font-black text-slate-950" type="submit">Create group</button></form></Card></section></>;
}
