import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { topicMastery } from "@/domain/mastery";
import { requireUser } from "@/lib/auth";

export default async function SharedProfilePage({ params }: { params: Promise<{ userId: string }> }) {
  const { userId } = await params; const { supabase } = await requireUser();
  const [{ data: profile }, { data: rows }, { data: awards }, { data: unlocks }] = await Promise.all([
    supabase.from("profiles").select("id,display_name,avatar_path,created_at").eq("id", userId).maybeSingle(),
    supabase.from("user_topic_mastery").select("*,topics(name)").eq("user_id", userId).order("updated_at", { ascending: false }),
    supabase.from("user_achievements").select("earned_at,achievements(name,description)").eq("user_id", userId).order("earned_at", { ascending: false }),
    supabase.from("pack_unlocks").select("unlocked_at,packs(name)").eq("user_id", userId).order("unlocked_at", { ascending: false }),
  ]);
  if (!profile) notFound();
  const stats = (rows ?? []).map((row) => ({ row, mastery: topicMastery({ topicId: row.topic_id, weightedSuccesses: Number(row.weighted_successes), weightedEvidence: Number(row.weighted_evidence), uniqueQuestions: row.unique_questions, correctAttempts: row.correct_attempts, totalAttempts: row.total_attempts, assistedCorrectAttempts: row.assisted_correct_attempts }) }));
  const attempts = stats.reduce((sum, item) => sum + item.row.total_attempts, 0); const correct = stats.reduce((sum, item) => sum + item.row.correct_attempts, 0); const points = stats.reduce((sum, item) => sum + Number(item.row.lifetime_points), 0);
  return <><header><p className="text-sm font-black uppercase tracking-[.2em] text-[var(--brand)]">Shared profile</p><h1 className="mt-2 text-4xl font-black">{profile.display_name}</h1><p className="mt-3 text-[var(--muted)]">Playing since {new Date(profile.created_at).toLocaleDateString()}</p></header><section className="mt-8 grid gap-4 sm:grid-cols-3"><Card className="p-5"><b className="text-3xl">{points.toLocaleString()}</b><p className="mt-1 text-sm text-[var(--muted)]">Lifetime points</p></Card><Card className="p-5"><b className="text-3xl">{attempts ? Math.round(correct / attempts * 100) : 0}%</b><p className="mt-1 text-sm text-[var(--muted)]">Raw accuracy</p></Card><Card className="p-5"><b className="text-3xl">{stats.reduce((sum, item) => sum + item.row.unique_questions, 0)}</b><p className="mt-1 text-sm text-[var(--muted)]">Unique questions</p></Card></section><section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><h2 className="text-xl font-black">Topic history</h2><div className="mt-5 space-y-4">{stats.map(({ row, mastery }) => { const topic = Array.isArray(row.topics) ? row.topics[0] : row.topics; return <div className="rounded-2xl bg-white/[.035] p-4" key={row.topic_id}><div className="flex justify-between"><b>{topic?.name ?? "Topic"}</b><b>{Math.round(mastery.proficiency * 100)}%</b></div><p className="mt-2 text-xs text-[var(--muted)]">{mastery.tier} · {row.unique_questions} unique · {Math.round(mastery.accuracy * 100)}% accuracy · {Number(row.lifetime_points).toLocaleString()} pts</p></div>; })}{!stats.length ? <p className="text-sm text-[var(--muted)]">No topic history yet.</p> : null}</div></Card><div className="space-y-6"><Card className="p-6"><h2 className="text-lg font-black">Achievements</h2>{awards?.map((award) => { const achievement = Array.isArray(award.achievements) ? award.achievements[0] : award.achievements; return <div className="mt-3" key={`${award.earned_at}-${achievement?.name}`}><b className="text-sm">{achievement?.name}</b><p className="text-xs text-[var(--muted)]">{achievement?.description}</p></div>; })}</Card><Card className="p-6"><h2 className="text-lg font-black">Packs</h2><div className="mt-3 flex flex-wrap gap-2">{unlocks?.map((unlock) => { const pack = Array.isArray(unlock.packs) ? unlock.packs[0] : unlock.packs; return <span className="rounded-full bg-white/5 px-3 py-1.5 text-xs font-bold" key={`${unlock.unlocked_at}-${pack?.name}`}>{pack?.name}</span>; })}</div></Card></div></section></>;
}
