export const TAXONOMY_AREAS = {
  "science-nature": [
    "Astronomy & Space",
    "Biology",
    "Botany",
    "Zoology",
    "Human Anatomy & Physiology",
    "Medicine & Health",
    "Chemistry",
    "Physics",
    "Earth Science",
    "Weather & Climate",
    "Ecology & Environment",
    "Mathematics",
    "Technology & Engineering",
    "Computing",
    "Scientific Discovery",
  ],
  history: [
    "Ancient History",
    "Medieval History",
    "Early Modern History",
    "Modern History",
    "United States History",
    "European History",
    "African History",
    "Asian History",
    "Latin American History",
    "Middle Eastern History",
    "Wars & Military History",
    "Politics, Law & Government",
    "Exploration, Trade & Empire",
    "Economic & Labor History",
    "Social & Cultural History",
    "Science & Technology History",
  ],
  geography: [
    "Countries & Borders",
    "Capitals & Cities",
    "Physical Geography",
    "Rivers & Lakes",
    "Oceans, Seas & Islands",
    "Mountains & Landforms",
    "Climate & Biomes",
    "Population & Human Geography",
    "Economic Geography",
    "Political Geography",
    "Maps & Navigation",
    "Landmarks & World Heritage",
  ],
  sports: [
    "Soccer",
    "Football",
    "Baseball & Softball",
    "Basketball",
    "Hockey",
    "Tennis & Racket Sports",
    "Golf",
    "Cricket & Rugby",
    "Athletics & Running",
    "Aquatic Sports",
    "Combat Sports",
    "Motor Sports",
    "Cycling",
    "Winter Sports",
    "Olympics & International Sport",
    "Rules, Records & Equipment",
  ],
  "arts-literature": [
    "Novels & Fiction",
    "Poetry",
    "Drama & Theatre",
    "Children's & Young Adult Literature",
    "Classical & Ancient Literature",
    "Authors & Literary History",
    "Painting",
    "Sculpture",
    "Architecture",
    "Photography",
    "Design & Decorative Arts",
    "Art Movements",
    "Museums & Masterworks",
    "Comics & Graphic Novels",
  ],
  "film-television": [
    "Film History & Classics",
    "Contemporary Film",
    "Directors & Filmmaking",
    "Actors & Performers",
    "Animation",
    "Documentary",
    "Science Fiction & Fantasy",
    "Horror & Thriller",
    "Comedy",
    "Drama",
    "Superheroes & Franchises",
    "Television Drama",
    "Television Comedy",
    "Reality, Game & Talk Shows",
    "Children's & Family Television",
    "Awards & Industry",
  ],
  music: [
    "Classical Music",
    "Opera",
    "Jazz",
    "Blues, Soul & R&B",
    "Rock",
    "Pop",
    "Hip-Hop & Rap",
    "Country & Folk",
    "Electronic & Dance",
    "World Music",
    "Musical Theatre & Soundtracks",
    "Music Theory & Terminology",
    "Instruments",
    "Composers & Songwriters",
    "Performers & Bands",
    "Albums, Songs & Recording History",
  ],
  "lifestyle-culture": [
    "Food & Drink",
    "Cooking & Cuisine",
    "Holidays & Celebrations",
    "Customs & Etiquette",
    "Religion & Belief",
    "Folklore & Traditions",
    "Language & Idioms",
    "Fashion & Dress",
    "Home & Daily Life",
    "Travel & Tourism",
    "Business, Brands & Consumer Culture",
    "Personal Finance & Work",
    "Games, Hobbies & Recreation",
    "Everyday Technology",
    "Education & Society",
    "Law & Civic Life",
    "Media & Internet Culture",
  ],
};

const rules = {
  "science-nature": [
    ["Computing", /comput|software|programming|internet|digital technolog|algorithm/i],
    ["Medicine & Health", /medic|health|disease|vaccine|public health|pharmac|epidemi|patholog/i],
    ["Human Anatomy & Physiology", /human biology|anatom|physiolog|neuro|brain|sens(?:e|ory)|cardio|respirat/i],
    ["Botany", /botan|plant|flora|tree|flower/i],
    ["Zoology", /zool|animal|mammal|bird|insect|reptile|fish|marine biology|animal taxonomy/i],
    ["Ecology & Environment", /ecolog|environment|conservation|ecosystem|biodiversity/i],
    ["Weather & Climate", /weather|climate|atmospher|meteorolog/i],
    ["Earth Science", /geolog|earth science|volcan|oceanograph|mineral|paleont|tectonic/i],
    ["Astronomy & Space", /astronom|space|planet|stellar|star|solar system|moon|cosmolog|black hole|orbital/i],
    ["Chemistry", /chemi|element|periodic|molecule|material science/i],
    ["Physics", /physic|mechanic|wave|sound|optic|electric|magnet|thermo|relativ|nuclear|particle/i],
    ["Mathematics", /math|geometry|algebra|statistic|number theor/i],
    ["Technology & Engineering", /engineer|technology|invention|structure|transport|aerospace|energy/i],
    ["Biology", /biolog|genetic|evolution|cell|microbio|biochem/i],
    ["Scientific Discovery", /science|scientist|discovery|research|scientific method/i],
  ],
  history: [
    ["Ancient History", /ancient|roman|greek|egypt|mesopotam|carthag|inca civilization|aztec/i],
    ["Medieval History", /medieval|middle ages|byzantine|viking/i],
    ["United States History", /united states|u\.s\.|american history|civil war|civil rights movement/i],
    ["African History", /afric|great zimbabwe|south african/i],
    ["Latin American History", /latin america|caribbean|inca history|aztec history|colonial latin/i],
    ["Middle Eastern History", /middle east|islamic history|ottoman|persian|safavid|turkish/i],
    ["Asian History", /asian|china|chinese|japan|japanese|india|indian|mongol|mughal|southeast asia|korea/i],
    ["European History", /europe|british|french|german|russian|italian|spanish|napoleon|reformation/i],
    ["Modern History", /modern|cold war|decolon|non-aligned|world events|turning points/i],
    ["Early Modern History", /early modern|renaissance|enlightenment|thirty years|atlantic world/i],
    ["Wars & Military History", /world war|military|battle|warfare|armed conflict/i],
    ["Politics, Law & Government", /politic|government|law|constitution|diplom|international organization/i],
    ["Exploration, Trade & Empire", /explor|trade|empire|imperial|coloni/i],
    ["Economic & Labor History", /economic|labor|industrial|business history/i],
    ["Science & Technology History", /science|technology|medical history|vaccination/i],
    ["Social & Cultural History", /social|cultural|religious|women|civil rights|education/i],
  ],
  geography: [
    ["Maps & Navigation", /map|navigation|coordinate|latitude|longitude|time zone/i],
    ["Landmarks & World Heritage", /landmark|world heritage|monument|natural wonder/i],
    ["Capitals & Cities", /capital|cit(?:y|ies)|urban/i],
    ["Countries & Borders", /countr|border|nation|state geography/i],
    ["Rivers & Lakes", /river|lake|freshwater/i],
    ["Oceans, Seas & Islands", /ocean|sea|island|strait|waterway|coast/i],
    ["Mountains & Landforms", /mountain|landform|desert|valley|canyon|plateau/i],
    ["Climate & Biomes", /climate|biome|polar|rainforest|tundra/i],
    ["Economic Geography", /economic|resource|agricultur|industry|trade/i],
    ["Political Geography", /political|territor|province|administrative/i],
    ["Population & Human Geography", /population|human geography|language|culture|migration/i],
    ["Physical Geography", /physical|geography|continent|region/i],
  ],
  sports: [
    ["Soccer", /association football|soccer|fifa|uefa/i],
    ["Football", /american football|gridiron|nfl|touchdown/i],
    ["Baseball & Softball", /baseball|softball|mlb/i],
    ["Basketball", /basketball|nba|free throw/i],
    ["Hockey", /hockey|nhl|stanley cup/i],
    ["Tennis & Racket Sports", /tennis|badminton|squash|table tennis|racket/i],
    ["Golf", /golf/i],
    ["Cricket & Rugby", /cricket|rugby/i],
    ["Athletics & Running", /athletic|track and field|running|marathon/i],
    ["Aquatic Sports", /swim|aquatic|water polo|diving|rowing|sailing/i],
    ["Combat Sports", /boxing|wrestling|martial|combat|judo|fencing/i],
    ["Motor Sports", /motor|racing|formula one|nascar|grand prix/i],
    ["Cycling", /cycl|tour de france/i],
    ["Winter Sports", /winter|ski|skating|biathlon|snowboard|curling/i],
    ["Olympics & International Sport", /olympic|international sport|world cup/i],
    ["Rules, Records & Equipment", /rule|record|equipment|officiat|signal|sports/i],
  ],
  "arts-literature": [
    ["Comics & Graphic Novels", /comic|graphic novel|manga/i],
    ["Children's & Young Adult Literature", /children|young adult/i],
    [
      "Classical & Ancient Literature",
      /classical literature|ancient literature|epic literature|myth|folklore|legend/i,
    ],
    ["Poetry", /poet|poetry|poem/i],
    ["Drama & Theatre", /drama|theatre|theater|playwright|shakespeare/i],
    ["Architecture", /architect/i],
    ["Photography", /photograph/i],
    ["Sculpture", /sculpt/i],
    ["Painting", /paint|painter/i],
    ["Design & Decorative Arts", /design|decorative|craft|fashion/i],
    ["Art Movements", /art movement|renaissance art|surreal|impression|modern art/i],
    ["Museums & Masterworks", /museum|masterwork|art history|visual art/i],
    ["Authors & Literary History", /author|literary history|literature|writer/i],
    ["Novels & Fiction", /novel|fiction|popular fiction/i],
  ],
  "film-television": [
    ["Animation", /animat/i],
    ["Documentary", /documentary/i],
    [
      "Directors & Filmmaking",
      /direct(?:or|ed|ing)|filmmak|cinematograph|screenwriting|production/i,
    ],
    [
      "Actors & Performers",
      /actor|actress|performer|casting|who (?:played|plays|portrayed|portrays|voiced|voices)|voice of/i,
    ],
    ["Superheroes & Franchises", /superhero|marvel|dc comics|franchise|star wars/i],
    ["Science Fiction & Fantasy", /science fiction|sci-fi|fantasy/i],
    ["Horror & Thriller", /horror|thriller/i],
    ["Reality, Game & Talk Shows", /reality|game show|talk show|quiz show/i],
    ["Children's & Family Television", /children|family television|kids/i],
    ["Television Comedy", /television comedy|sitcom/i],
    ["Television Drama", /television drama|tv drama/i],
    ["Comedy", /comedy|comedian/i],
    ["Drama", /drama/i],
    ["Awards & Industry", /award|industry|box office|emmy|oscar/i],
    ["Film History & Classics", /classic film|film history|silent film|cinema history/i],
    ["Contemporary Film", /film|movie|television|tv/i],
  ],
  music: [
    ["Opera", /opera/i],
    ["Musical Theatre & Soundtracks", /musical theatre|soundtrack|film music/i],
    ["Music Theory & Terminology", /theory|terminology|notation|harmony|rhythm/i],
    ["Instruments", /instrument|guitar|piano|string|brass|woodwind|percussion/i],
    ["Composers & Songwriters", /composer|songwriter/i],
    ["Albums, Songs & Recording History", /album|song|recording|chart|music history/i],
    [
      "Performers & Bands",
      /performer|band|vocalist|singer|duo|group|artist|who (?:recorded|released|sang|performed)/i,
    ],
    ["Classical Music", /classical|symphon|orchestra|baroque/i],
    ["Jazz", /jazz/i],
    ["Blues, Soul & R&B", /blues|soul|r&b|rhythm and blues/i],
    ["Hip-Hop & Rap", /hip-hop|hip hop|rap/i],
    ["Rock", /rock|punk|metal|alternative|grunge/i],
    ["Country & Folk", /country|folk|bluegrass/i],
    ["Electronic & Dance", /electronic|dance|disco|techno|house music/i],
    ["World Music", /world music|reggae|latin music|african music|scottish music/i],
    ["Pop", /pop|popular music/i],
  ],
  "lifestyle-culture": [
    ["Cooking & Cuisine", /cook|cuisine|recipe|baking|fermentation/i],
    ["Food & Drink", /food|drink|beverage|dining|coffee|tea/i],
    ["Holidays & Celebrations", /holiday|celebration|festival/i],
    ["Customs & Etiquette", /custom|etiquette|social practice/i],
    ["Religion & Belief", /religion|belief|faith|worship/i],
    ["Folklore & Traditions", /folklore|myth|tradition|legend/i],
    ["Language & Idioms", /language|idiom|word|phrase|writing system/i],
    ["Fashion & Dress", /fashion|dress|clothing|textile/i],
    ["Travel & Tourism", /travel|tourism|theme park|hotel/i],
    ["Business, Brands & Consumer Culture", /business|brand|consumer|company|advertis/i],
    ["Personal Finance & Work", /finance|money|work|career|employment/i],
    ["Games, Hobbies & Recreation", /game|hobb|recreation|chess|go|craft/i],
    ["Everyday Technology", /technology|internet|device|transportation/i],
    ["Education & Society", /education|school|society|social institution/i],
    ["Law & Civic Life", /law|civic|government|public life/i],
    ["Media & Internet Culture", /media|internet culture|broadcast|social media/i],
    ["Home & Daily Life", /home|daily life|household|lifestyle|culture/i],
  ],
};

const fallbackAreas = {
  "science-nature": "Scientific Discovery",
  history: "Social & Cultural History",
  geography: "Physical Geography",
  sports: "Rules, Records & Equipment",
  "arts-literature": "Authors & Literary History",
  "film-television": "Contemporary Film",
  music: "Performers & Bands",
  "lifestyle-culture": "Home & Daily Life",
};

const discardedDetailLabels = new Set([
  "animals",
  "art",
  "film",
  "general knowledge",
  "geography",
  "history",
  "lifestyle & culture",
  "literature",
  "music",
  "science",
  "sports",
  "television",
  "world events",
  "world geography",
]);

const detailAliases = new Map([
  ["visual art", "Visual Arts"],
  ["popular music", "Pop Music"],
  ["mesopotamia", "Ancient Mesopotamia"],
  ["u.s. history", "United States History"],
  ["us history", "United States History"],
]);

function normalized(value) {
  return value.trim().normalize("NFKC").toLocaleLowerCase("en-US");
}

export function normalizeQuestionTaxonomy(question) {
  const areas = TAXONOMY_AREAS[question.topicSlug];
  if (!areas) throw new Error(`Unknown taxonomy topic: ${question.topicSlug}`);
  const labels = [...(question.subtopics ?? [])];
  const explicitArea = question.subtopic?.trim();
  const haystacks = [...labels, question.prompt, question.canonicalAnswer];
  const area =
    (explicitArea && areas.includes(explicitArea) ? explicitArea : null) ??
    areas.find((candidate) =>
      labels.some((label) => normalized(label) === normalized(candidate)),
    ) ??
    rules[question.topicSlug].find(([, pattern]) =>
      haystacks.some((value) => pattern.test(value)),
    )?.[0] ??
    fallbackAreas[question.topicSlug];

  const detailTags = [...labels, ...(question.detailTags ?? [])]
    .map((label) => label.trim())
    .filter(Boolean)
    .filter((label) => !discardedDetailLabels.has(normalized(label)))
    .map((label) => detailAliases.get(normalized(label)) ?? label)
    .filter((label) => normalized(label) !== normalized(area));
  const uniqueDetailTags = detailTags.filter(
    (label, index, values) =>
      values.findIndex(
        (candidate) => normalized(candidate) === normalized(label),
      ) === index,
  );

  return {
    subtopic: area,
    detailTags: uniqueDetailTags.slice(0, 8),
  };
}
